const { ApolloServer, gql } = require("apollo-server");
const db = require("./models");
const { Link } = db;

const generateSlug = () => {
  var chars = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNPQRSTUVWXYZ";
  var slug = "";
  const randIdx = () => Math.floor(Math.random() * chars.length);
  for (var i = 0; i < 4; i++) {
    slug += chars[randIdx()];
  }
  return slug;
};

const isNewSlug = async (slug) => {
  const isUsed = await Link.findOne({
    where: { slug }
  });
  console.log(isUsed);
  return isUsed ? false : true;
};

const verifySlug = (slug) => {
  const regexExp = /^[A-Za-z0-9]+(?:-[A-Za-z0-9]+)*$/g;
  const autoGenerated = generateSlug();
  return regexExp.test(slug) && isNewSlug(slug)
    ? slug
    : verifySlug(autoGenerated);
};

const typeDefs = gql`
  type Link {
    url: String
    slug: String
  }

  type Query {
    links: [Link]
  }

  type Mutation {
    createLink(url: String!, slug: String!): Link!
  }
`;

const resolvers = {
  Query: {
    links: async () => {
      return await Link.findAll();
    }
  },
  Mutation: {
    async createLink({ url, slug }) {
      console.log("link has been created", url, slug);

      return Link.create({
        url,
        slug: verifySlug(slug)
      });
    }
  }
};

const server = new ApolloServer({
  typeDefs,
  resolvers
});

server.listen().then(({ url }) => {
  console.log(`🚀 Server ready at ${url}`);
});

// const resolvers = {
//   Query: {
//     async user(root, { id }, { models }) {
//       return models.User.findById(id);
//     },
//     async allRecipes(root, args, { models }) {
//       return models.Recipe.findAll();
//     },
//     async recipe(root, { id }, { models }) {
//       return models.Recipe.findById(id);
//     },
//   },
// };
